### ISSUE TITLE
`riak-repl start-fullsync` does nothing on non-leader node 

### ISSUE THREAD

**Issue by fprimex** [basho/riak_repl#100]
Running `riak-repl start-fullsync` on a node in the cluster that is not the replication leader results in no messages and no actions. Preferable behavior would be to either communicate with the leader to start a fullsync, or return a message stating that no action is being taken and that the command should be run on the leader (and/or log the message).

**Comment by angrycub** [comment]
referred to by https://github.com/basho/riak_ee-issues/issues/8

**Comment by cmeiklejohn** [comment]
I'm almost positive this works correctly on 2.0, given that most of the riak-repl commands are proxied to the leader node.  I'm moving this to resilience and making it part of the testing work.

**Comment by cmeiklejohn** [comment]
OK, I confirmed this is a problem, but only with v2 MDC replication.  Given that v2 replication is deprecated, I'm going to consider this something we won't fix.  But, I'll give @jonmeredith the last word. :)

**Comment by jonmeredith** [comment]
Do not fix v2
