### ISSUE TITLE
Add mechanism to indicate if objects were dropped and a fullsync is needed

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#142]
Currently, if we drop objects from realtime replication (BNW), we may in some cases be able to observe the drop. Relevant error messages:
- No nodes available to migrate replication data (on shutdown)
- No available nodes to proxy <count> objects to (on shutdown)
- rtq proxy target <node> is down (on shutdown)

However, if a node crashes during realtime replication, we can't write to the logfile and there is no indication of dropped objects on restart.

At least one customer (Anya) wants to be able to detect the need for a full sync by monitoring repl_stats (json) in their operational environment, since they have already built mechanisms to trigger alarms based off polling each node.

We already have a dropped object count in the status. This will monitors drops due to connection loss, connection errors, overloaded nodes, and anything else that happens while running.

We may need to add an entry to stats for dropped objects during controlled or uncontrolled shutdowns. A completely crashed node that never comes back obviously can't indicate drops. But perhaps the other end of the connection can mark the loss of connection.

**Comment by buddhisthead** [comment]
Customer ticket http://help.basho.com/tickets/3399

**Comment by bookshelfdave** [comment]
We are adding a riak-repl status/JSON param that shows if a fullsync is needed.

They will need to monitor source and sink clusters and fullsync if any node has a non-zero value for the fullsync_needed stat.

**Comment by bookshelfdave** [comment]
See: https://github.com/basho/riak_repl/pull/145

**Comment by bookshelfdave** [comment]
This issue has been resolved by: https://github.com/basho/riak_repl/pull/152
