### ISSUE TITLE
realtime replication does not automatically connect to a sink when a node is added

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#143]
When a new node is joined to an existing cluster, the new node does not automatically connect to a node in the sink cluster when RT replication is enabled. This makes it impossible to add nodes to a running cluster without having to stop/start RT replication, which means objects written to the new node will not be RT replicated. This is bad. This should be fixed.

**Comment by buddhisthead** [comment]
Customer ticket:
https://help.basho.com/tickets/3414

**Comment by bookshelfdave** [comment]
@buddhisthead can you add the PR that fixed this as a comment and close the issue?
