### ISSUE TITLE
All RT source nodes connect to same sink when bouncing the source cluster

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#146]
from ZenDesk https://help.basho.com/tickets/3441

Apple had a 48-node cluster (the source) and bounced each node in 5 minute intervals. After each bounced node came back up, the realtime sync source connected to the same realtime sync sink on the remote cluster (the sink). This is bad because it could have overloaded the one sink node. After all nodes were bounced, every source was connected to the same single sink node.

The reason is that the cluster manager was giving out the same list of IP addresses to each source node as it came back up, as the locator for realtime sync. Even though the round-robin balancer was working, it was getting reset every 5 seconds by the remote node polling update (polls IP address of the remote cluster every 5 seconds). The current cluster manager assumes the list returned by the remote cluster is in an order of least busy to most busy, but that is not actually implemented yet. So, the remote just returns the same list every time and hence it's not actually balanced. Bah.

Two solutions come to mind:
1. have the remote send over a list that correctly reflects busy-ness
2. have the local cluster not re-order the list on updates. Just store the IP addresses

Solution 2 is easier I think. But we'll see.

**Comment by buddhisthead** [comment]
So, I think only solution 1 will work. The reason is that the new node usually gets elected as the leader. This is sad because the new node then gets a fresh list from the remote cluster and all round robin state is lost.

**Comment by bookshelfdave** [comment]
fixed in https://github.com/basho/riak_repl/pull/150
