### ISSUE TITLE
BNW Large Scale Testing on AWS

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#161]
@jsmartin is working on deployment tools
@buddhisthead is testing the tools and trying to build repl clusters

**Comment by jaredmorrow** [comment]
I'm so excited about this.

**Comment by bookshelfdave** [comment]
@cmeiklejohn @lordnull ok to close this one as it's part of the larger testing initiative?

**Comment by cmeiklejohn** [comment]
Yes.
