### ISSUE TITLE
Proxy get integration in BNW

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#162]

**Comment by bookshelfdave** [comment]
"Real-time sync is triggered when an update is sent from a client to a primary Riak CS implementation. Once replicated in the first location, the updates are streamed in real-time to the secondary site. But what happens if a client requests an object from the secondary cluster and not all of its blocks have been replicated to that cluster? With Riak multi-site replication, the secondary cluster will request any missing blocks from the primary cluster so that the client can be served."

See Real Time Sync Mode:
http://docs.basho.com/riakcs/latest/cookbooks/MDC-Overview/

**Comment by buddhisthead** [comment]
Resolved by https://github.com/basho/riak_repl/pull/276 and other related PRs.
