### ISSUE TITLE
Cascading writes

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#167]
REDACTED/REDACTED/REDACTED

**Comment by angrycub** [comment]
REDACTED is looking for this feature as well

**Comment by bookshelfdave** [comment]
@lordnull would you mind adding a high level description that the CSE's can use if they need to describe this feature to a customer?

**Comment by lordnull** [comment]
How's the following?

Cascading real time is a way to allow real time synchronization amoung multiple clusters without needing to have create a net of the clusters.

Given:
Clusters A, B, and C,
A, B, and C all have the cascading capability and enabled.
A real time replicates to B
B real time replicates to C
C real time replicates to A
Data d is written to A
Means:
Replication of d from A to B occurs
Replication of d from B to C occurs
Replication of d from C to A _does not_ occur

```
Data d => A replicates -> B replicates -> C
```

A cluster can be set to not cascade:

Given:
Clusters A, B, and C,
Cluster B either does not have the cascading capability or it is not enabled.
A real time replicates to B
B real time replicates to C
C real time replicates to A
Data d is written to A
Data e is written to B
Means:
Replication of d from A to B occurs
Replication of d from B to C _does not occur_
Replication of e from B to C occurs
Replication of e from C to A occurs
Replication of e from A to B _does not_ occur

```
Data d => A replicates -> B
Data e => B replicates -> C replicates -> A
```

Clusters need not be in a circle:

Given
Clusters A, B, C, and D
A replicates to B and C
B and C both replicate to D
Data d is written to A
Means:
Replication of d from A to B occurs
Replication of d from A to C occurs
Replication of d from either B or C to D occurs (but not both)

```
Data d => A replicates -> B,C replicates -> D
```
