### ISSUE TITLE
BNW Bootstrap mode

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#168]
REPL to an empty cluster is incredibly inefficient. Provide a bootstrap command that blasts all data to a second cluster.

**Comment by cmeiklejohn** [comment]
Moving to 2.1; curious as to what is actually desired here.

**Comment by bookshelfdave** [comment]
might want to ask @Vagabond

**Comment by Vagabond** [comment]
it is less of an issue with AAE, if AAE ever worked right, but with keylist we do a lot of inefficient compares that soak up a lot of time even when we _know_ the sink cluster is empty.

**Comment by engelsanchez** [comment]
The new AAE fullsync work has made it much more efficient to bootstrap an empty cluster. Closing for now. Further improvements can be tracked in newer issues.

**Comment by cmeiklejohn** [comment]
:+1:
