### ISSUE TITLE
Clean up riak-repl command line output

### ISSUE THREAD

**Issue by angrycub** [basho/riak_repl#190]
Using `riak-admin cluster` as inspiration, clean up and add text to the output of `riak-repl` to make it more user-friendly.

**Comment by bookshelfdave** [comment]
See https://github.com/basho/riak_ee/pull/128

**Comment by angrycub** [comment]
:+1:  +1... That's awesome!

**Comment by bookshelfdave** [comment]
@angrycub was that +1 intended for the PR or the issue?

**Comment by bookshelfdave** [comment]
PR merged
