### ISSUE TITLE
BNW real-time postcommit hook called on "old" style cluster

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#195]
@kellymclaughlin found an issue while running a replication riak_test against CS, using old 1.2 repo configuration (what is now called "default" - not 1.3 BNW).

A bunch of repeated errors showed up in the logs list this:

2013-02-06 16:34:05.681 [debug] <0.5494.0>@riak_kv_put_fsm:decode_postcommit:781 Problem invoking post-commit hook riak_repl2_rt:postcommit -> error:badarg

Looking into it, the only way I can see this getting hit is when BNW postcommit has been installed into the bucket properties, because that is a riak_repl2_rt:postcommit() call. The badarg is a mystery to me, though.

```
When I look at the code path, it includes a call here:
get_modes(Ring) ->
    RC = get_repl_config(Ring),
    case dict:find(repl_modes, RC) of
        {ok, ReplModes} -> ReplModes;
        error ->
            %% default to mixed modes
            [mode_repl12, mode_repl13]
    end.
```

Is it possible that we aren't finding repl_modes in the ring? Makes me wonder if the default should really be mixed modes until we officially support BNW in 1.4.

This doesn't seem to be causing any tests to fail, so it's not data-loss or corruption, and is thus being marked as a MUST for 1.3, but I think we should investigate for 1.4.

**Comment by buddhisthead** [comment]
From @kellymclaughlin 

```
{postcommit,[{struct,[{<<"mod">>,<<"riak_repl_leader">>},
                       {<<"fun">>,<<"postcommit">>}]},
              {struct,[{<<"mod">>,<<"riak_repl2_rt">>},
                       {<<"fun">>,<<"postcommit">>}]}]},
```

Most definitely has the BNW commit hooks installed.

**Comment by cmeiklejohn** [comment]
Moving to 2.1.

**Comment by engelsanchez** [comment]
This sounds like the problem with the hooks not being updated properly I found and Jon fixed in https://github.com/basho/riak_repl/pull/589. Closing unless new information surfaces
