### ISSUE TITLE
riak_test for binary object downgrade while repl running

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#205]
It's possible to downgrade a cluster from "new" binary riak object format back to the old t2b form. There is already a test for that in riak_kv. However, a downgrade should also work while replication is running, so let's write a test for that.

**Comment by cmeiklejohn** [comment]
Added as resilience test for RC.

**Comment by cmeiklejohn** [comment]
Taking this next.

**Comment by jrwest** [comment]
are we sure this even applies version wise anymore? How far can one roll back w/ Riak 2.0?

**Comment by cmeiklejohn** [comment]
1.3, I presume.  What version did the format change at?

**Comment by jrwest** [comment]
1.4 [1]. I didn't realize we were doing 2 versions back as well

[1] https://github.com/basho/riak/blob/develop/RELEASE-NOTES.md#improved-binary-format

**Comment by cmeiklejohn** [comment]
I thought so.  Maybe @jonmeredith can confirm.

**Comment by jrwest** [comment]
agreed. fwiw, my assumption was 2 vsns forward 1 vsn back (e.g. last stable release). im probably wrong.

**Comment by jonmeredith** [comment]
the principle is that if your upgrade is botched then you should be able to
get back where you were.  Based on that, it should be two forward, two back.

On Thu, Apr 17, 2014 at 8:42 AM, Jordan West notifications@github.comwrote:

> agreed. fwiw, my assumption was 2 vsns forward 1 vsn back (e.g. last
> stable release). im probably wrong.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak_repl/issues/205#issuecomment-40721512
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by cmeiklejohn** [comment]
Working on tracking this in basho/riak_test#587.
