### ISSUE TITLE
Riak CS bucket replication controls

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#223]
Old Desc: Control which _Riak_ buckets are replicated w/ realtime/fullsync via cluster metadata
New Hotness: Generic 'reduced replication' system

Branches/pull breakdown:
- [x] https://github.com/basho/riak_kv/tree/mw-reduced-repl (pull request: https://github.com/basho/riak_kv/pull/661)
- [x] https://github.com/basho/riak_test/tree/feature/mw-reduced-repl (pull request: https://github.com/basho/riak_test/pull/384)
- [x] https://github.com/basho/riak_repl/tree/feature/mw-reduced-repl (pull request: https://github.com/basho/riak_repl/pull/402)
- [x] https://github.com/basho/riak_ee/tree/feature/mw-reduced-repl (pull request: https://github.com/basho/riak_ee/pull/170)

**Comment by bookshelfdave** [comment]
(moved from main description)
Meeting notes from data pipe. March 21, 2013

This is just a blanket issue to cover the initial conversation with the customer.
- Replication of user credentials across all data centers, but not their data.
- Multi-site (user credentials and non-space-explosion for user-data-replication)
- Design for future growth.

Needs 9 immutable URLs to represent their data centers.
Need single end-point per logical data center they have.
Want multiple clusters under a single cluster. balance and deploy as they grow. They need a design that shows them how to expand. They just need to know that we are getting ahead of the scaling problem.
Wants Basho to tell them how to design a cluster that will be growing quickly.

All users need to be able to use one set of credentials across all data centers.

Cost per GB would be 9x if they have to replicate all buckets across all clusters, so they want to be able to specify bucket replication. This will save them a lot of space.

Customer felt that they had a lot of sales pressure onto them. I'm in a tough spot and you've got to give me something to help me out. Give me a design. Show me a roadmap that can expand as we grow.

Some initial notes from Jon:

Medium-term idea
  - extend Riak Replication to add replication policy by bucket,
    which data centers the _riak_ bucket will be sent to
  - make RiakCS modify Riak bucket properties when S3 bucket policy
    changes (updates to 0o<s3name hash> and 0b<hash> riak buckets)
  - update CS garbage collection to check bucket policy and remove
    data once it is no longer replicated to that DC (could also
    remove deleted accounts too?)
Questions:
User bucket
  - does it matter if we replicate all users everywhere and
    restrict where they login?
Clarify requirement:
  - If a bucket was replicated to DC1 and DC2 then changed to only
    DC2, would you expect the data to be removed from DC1.

**Comment by bookshelfdave** [comment]
See: https://gist.github.com/Vagabond/658074a3ba260787bf08

The team has decided on implement "the 'better' way", starting with @lordnull's work on https://github.com/basho/riak_kv/tree/mw-reduced-repl

**Comment by lordnull** [comment]
Branches associated with the feature:

https://github.com/basho/riak_kv/tree/mw-reduced-repl
https://github.com/basho/riak_test/tree/feature/mw-reduced-repl
https://github.com/basho/riak_repl/tree/feature/mw-reduced-repl
https://github.com/basho/riak_ee/tree/feature/mw-reduced-repl

**Comment by lordnull** [comment]
All things checked and completed. At this point, if new issues with the feature are discovered, new issues should be opened.
