### ISSUE TITLE
Get rid of the recusive functions and replace them with OTP behaviours

### ISSUE THREAD

**Issue by Vagabond** [basho/riak_repl#230]
There's recursive functions spawned by proc_lib:start_link in riak_core_connection and riak_core_connection_manager.

You're only supposed to use proc_lib if your process adheres to OTP principles, which these don't, for example there's no support for system messages.

There also seems little reason NOT to rewrite them as real OTP behaviours. I recommended this earlier, before BNW merged, but we didn't have the time to address it then.

**Comment by cmeiklejohn** [comment]
Moving to 2.1 as part of the scheduled cluster and connection manager work.

**Comment by lordnull** [comment]
https://github.com/basho/riak_repl/pull/631 resolves this.
