### ISSUE TITLE
client_stats reporting 'connecting' site after site is deleted

### ISSUE THREAD

**Issue by jcapricebasho** [basho/riak_repl#234]
Sometimes, sites deleted via `riak-repl del-site <site_name>` are persisting in client_stats when deleted in the 'connecting' state.
1.  Add offline cluster as site
    `dev/dev4/bin/riak-repl add-site 127.0.0.1 9010 break`
2.  Delete site
    `dev/dev4/bin/riak-repl del-site break`

Sometimes client_stats reports no sites, other times the site persists.

However, the site is always removed from the ring, confirmed by running:

```
{ok, Ring} = riak_core_ring_manager:get_my_ring().
RC = riak_repl_ring:get_repl_config(Ring).
Sites = dict:fetch(sites, RC).
```

before and after running riak-repl del site.

Sometimes, client_stats still shows Riak is attempting to connect to the site.  The riak_repl_tcp_client representing that site still exists as a child of riak_repl_client_sup after riak-repl del-site is executed in these situations.  The occurrences of this are inconsistent.

Reported in ticket #4183:
https://basho.zendesk.com/agent/#/tickets/4183

**Comment by Vagabond** [comment]
I investigated this a bit, and I don't see why this would happen. When riak_repl_leader:ensure_sites is called, it should take care of this.

Don't have time to investigate more now.

**Comment by jcapricebasho** [comment]
https://github.com/basho/riak_ee-issues/issues/4 covers this issue publicly.

**Comment by cmeiklejohn** [comment]
Moving to 2.0-RC for investigation under resilience work so existing behavior can be documented.

**Comment by cmeiklejohn** [comment]
Taking this one.

**Comment by cmeiklejohn** [comment]
Wow, I just now realized that this original issue is filed for v2 repl.  Given it's been deprecated for the 2.0 release cycle, I'm actually going to just close this out with a wontfix.  cc: @jonmeredith

**Comment by jonmeredith** [comment]
Concur
