### ISSUE TITLE
Partitions skipped when location_down during full sync

### ISSUE THREAD

**Issue by lordnull** [basho/riak_repl#242]
When doing a fullsync, if a partition's node on the sink side is down, that partition is skipped entirely. The only evidence is a log message and queued/in-progress stat changes. A better solution is to track location downs in a stat, as well as retry the partition later.

**Comment by cmeiklejohn** [comment]
Is this still true?  This should be tested for 2.0 and documented if that is the case.

**Comment by cmeiklejohn** [comment]
@lordnull Any thoughts here?

**Comment by lordnull** [comment]
As far as I know, there have been no changes, but it's worth a double check.

**Comment by lordnull** [comment]
Checking this out, while there seems to be a log message in the code, I don't think the code path is ever hit. The number of partitions queued and at successful exits will be lower (excluding partitions on downed nodes).

**Comment by cmeiklejohn** [comment]
Assigning to @cmeiklejohn.

**Comment by cmeiklejohn** [comment]
It appears what we want here is an intercept on node_reserver to force both busy and down messages.

**Comment by cmeiklejohn** [comment]
Looks like the code has handling for a `down` message being returned from reserve, but it looks like the node reserver can't ever return that, given it's implementation.  

However, I wrote a r_t to play around with returning `busy` message, and it triggers infinite retries, (ie. fullsync does not complete unit the partition is available) which I assume is the desired behavior, so I'm closing this out as a non-issue unless I'm not testing the correct thing.

@jonmeredith @lordnull, thoughts?  If we feel a change is desired here, I can reopen.

**Comment by cmeiklejohn** [comment]
Re-opening.  I believe my testing was incorrect and I'm going to dig into this some more.

**Comment by cmeiklejohn** [comment]
I've been able to reproduce this and I'm currently working on a fix.

**Comment by cmeiklejohn** [comment]
https://github.com/basho/riak_test/pull/617
https://github.com/basho/riak_repl/pull/590
