### ISSUE TITLE
bad argument in call to erlang:binary_to_term(etimedout) in riak_repl2_fscoordinator:handle_info/2 line 404

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#251]
> console_log_2013-04-18.log:2013-04-18 14:52:46.383 [error] <0.28009.1350> gen_server <0.28009.1350> terminated with reason: bad argument in call to erlang:binary_to_term(etimedout) in riak_repl2_fscoordinator:handle_info/2 line 404

https://basho.zendesk.com/agent/#/tickets/4341

**Comment by bookshelfdave** [comment]
fixed in https://github.com/basho/riak_repl/pull/250

**Comment by bookshelfdave** [comment]
this still in an issue?
cc @lordnull

**Comment by lordnull** [comment]
Do we have further reports of this being an issue? The referenced pr made it into develop and 1.4. The line mentioned in the error no longer matches up with code, so unless we have a specific recent incident, as tar as I know this is resolved.
