### ISSUE TITLE
riak_core_cluster_mgr state corrupted when restarted by supervisor

### ISSUE THREAD

**Issue by Vagabond** [basho/riak_repl#255]
riak_core_cluster_mgr_sup is a rest_for_one supervisor, which means if riak_core_service_mgr or the riak_core_cluster_mgr itself crash, the riak_core_cluster_mgr will be restarted.

This is all fine and well, except that when the riak_core_cluster_mgr starts. it installs default stub resolution functions. It expects that the riak_repl application start process will register real resolution functions later. However, for a supervisor restart, this does not happen, so the stub functions remain.

This means that if you can crash the service or cluster manager, that node will no longer behave correctly. The most obvious symptom is that, when asked for a list of IPs in the cluster, it will return the empty list.

When this happens, riak-repl connect IP:Port will initially connect, but when it tries to pull the list of IPs from the other cluster to do the second phase connect (where it connects by cluster name), it will try to connect to a cluster with no known IPs.

This will then lead to 'riak-repl connections' showing no active connections, but attempts to reconnect will fail with 'already connected' since in the background we're trying to connect to this IP-less cluster.

There are various approaches to fix this, including:
- Hardcode the funs, make them pluggable later
- Add another child process to the riak_core_cluster_mgr_sup that registers the funs as part of its startup, so when the rest_for_one triggers, it is restarted as well
- Store the funs in an ETS table owned by some other process that isn't likely to restart, the riak_core_cluster_mgr_sup itself is a good candidate for this

**Comment by buddhisthead** [comment]
Resolved by PR #257
