### ISSUE TITLE
Configurable cipher suites for SSL connections

### ISSUE THREAD

**Issue by Vagabond** [basho/riak_repl#290]
As mentioned by Engine Yard, PCI compliance requires the use of only certain ciphers.

**Comment by bookshelfdave** [comment]
@Vagabond should this be moved to riak_core?

**Comment by Vagabond** [comment]
Probably, yes. This is also relevant for client security.

**Comment by bookshelfdave** [comment]
actually, moved to https://github.com/basho/platform_tasks/issues/47
