### ISSUE TITLE
riak-repl status fullsync_coordinator successful_exits off by -1 with no errors

### ISSUE THREAD

**Issue by jcapricebasho** [basho/riak_repl#295]
successful_exists is reported as ring_creation_size - 1 when no errors are reported.

https://github.com/basho/riak_repl/blob/1.3.1/src/riak_repl2_fscoordinator.erl#L351

notify_rt_dirty_nodes is being called with State, which does not include the final value of successful_exits (set in State2)

**Comment by jcapricebasho** [comment]
https://github.com/basho/riak_ee-issues/issues/6

**Comment by buddhisthead** [comment]
@jcapricebasho :
- https://github.com/basho/riak_repl/blob/1.3.1/src/riak_repl2_fscoordinator.erl#L346
- notify_rt_dirty_nodes(State) should this be State2?

@lordnull:
- I think you have found the bug. That would cause a consistent off by one error on completion.

**Comment by buddhisthead** [comment]
Resolved by PR #310
