### ISSUE TITLE
Visibility into object replication status

### ISSUE THREAD

**Issue by michellep-basho** [basho/riak_repl#308]
Request from Shantu Roy of Tier 3 to be able to view the replication status of an individual object. Note that they are using Riak CS, but Kelly recommended that I log it in one of the Riak repos as it may be better handled on the Riak side. thanks

**Comment by michellep-basho** [comment]
I followed up with Shantu after Jon said that the work to implement this would be complicated.  He said that while this would be the ideal scenario, he would be OK with the ability to see aggregated replication stats on a per bucket or per tenant basis.  Let me know if this is a more reasonable request.  thanks

**Comment by michellep-basho** [comment]
I can move this to CS repo if the work will occur there.

**Comment by cmeiklejohn** [comment]
Moving to the 2.1 milestone.

**Comment by engelsanchez** [comment]
The request as stated doesn't seem feasible.  Does anybody remember exactly what information, what fields they wanted to see? I'm closing this in favor of the new (giant task) of providing more information about [how up to date clusters are](https://github.com/basho/riak_repl/wiki/MDC4_MajorTasks#l4---improved-visibility-into-how-up-to-date-clusters-are).  Feel free to add more specifics of this request and I'll make sure it ends up in the new issue.
