### ISSUE TITLE
Can't cancel, pause fullsync (both default and advanced)

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_repl#323]
see ZD #5028 , there're logs.

`riak_repl_keylist_server:bloom_fold/3` calls `gen_fsm:sync_send_event/3` to keylist server. When it is in `wait_for_partition` state, this server crashes because there's no `wait_for_partition/3`.

Its solution would be adding `wait_for_partition/3` or stop using `sync_send_event` or anything else.

**Comment by cmeiklejohn** [comment]
Moving to 2.0-RC.
