### ISSUE TITLE
Deprecate version 2 replication

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#335]

**Comment by cmeiklejohn** [comment]
Added deprecation warning for 2.0.  Will remove in future release.

**Comment by bookshelfdave** [comment]
https://github.com/basho/riak_repl/pull/487
https://github.com/basho/riak_ee/pull/203

**Comment by cmeiklejohn** [comment]
see https://github.com/basho/riak_repl/pull/487
