### ISSUE TITLE
Add calls to background manager for vnode overload protection

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#337]
Make fullsync replication cooperate nicely with other background jobs, e.g. handoff, AAE manager, and extract/load.

**Comment by cmeiklejohn** [comment]
Not even sure what the work here is, maybe someone can clarify?  Moving out to the 2.1 milestone.

**Comment by engelsanchez** [comment]
This looks like a personal TODO item from Chris T.  The future of the background manager is very uncertain at this point anyway. Closing.
