### ISSUE TITLE
Address urgent customer issues in 1.3.2

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#339]
AKA: 1.3.3 release notes
- [x] increase the cluster manager timeouts as in 1.4 (https://github.com/basho/riak_repl/pull/344) (https://github.com/basho/riak_repl/pull/343)
- [x] address the formatting of that _ts stat crash (https://github.com/basho/riak_repl/pull/342)
- [x] dont' crash on stats poll (https://github.com/basho/riak_repl/pull/345)
- [ ] 1.3.3 release notes (https://github.com/basho/internal_wiki/wiki/Riak-1.3.3-release-notes-(Enterprise-only))
- [x] https://github.com/basho/riak_repl/pull/360
- [x] https://github.com/basho/riak_repl/pull/353
- [x] https://github.com/basho/riak_repl/pull/364
- [x] https://github.com/basho/riak_repl/pull/366
- [ ] email dev@ and TAMs

Note: .beams built with R15B01 + scheduler patch
Note: See https://github.com/basho/riak_repl/issues/359 for more info regarding realtime overflow 
Note: https://github.com/basho/riak_repl/pull/344 won't be included in beams shipped to OpenX, however riak_core_cluster_manager WILL be to increase timeout

**Comment by buddhisthead** [comment]
With all PRs of this issue addressed, I think we can close this out now.

**Comment by buddhisthead** [comment]
Re-open to track https://github.com/basho/riak_repl/pull/345, which I think should be added.

**Comment by lordnull** [comment]
#345 has been merged, so all are checked again.

**Comment by bookshelfdave** [comment]
See release notes at https://github.com/basho/internal_wiki/wiki/Riak-1.3.3-release-notes-(Enterprise-only)

**Comment by bookshelfdave** [comment]
See also 1.4.1 issues list: https://github.com/basho/riak_repl/issues/362
