### ISSUE TITLE
Prevent RT overload

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#359]
# Prevent RT Overload

This issue is based on observations from two serpate customer issues that occured on riak_ee version 1.3.2 (Symantec and OpenX).
## Conditions
- AAE + RT repl
- Heavy write load to source cluster, which creates heavy RT I/O
- balanced number of nodes on source and sink (thus 1:1 RT connection ratio)
## Symptoms:
- Stable cluster, running some AAE build-trees, default concurrency and frequency
- Excessive memory consumption after turning on RT replication.
- After a few minutes, we observe multiple RT connections on the sink nodes
## Theory: (summary/edit of the Hipchat transcript with OpenX on Aug-02 14:34)

The source connects to the sink (RT), and the source starts blasting RT objects over the wire.
We have TCP in "active true" mode, which means that when the packets get delivered to the sink side,
the operating system and erlang runtime system will just shove them into the RT sink process's mailbox.
Even if the RT sink process is overloaded with work, or it can't "put" fast enough to the cluster,
the TCP packets just keep on coming. which is sad on so many levels.

The mailbox can back up on the sink side, which means we have all those binary objects being held in memory.
This might explain the memory explosion. Also, since the sink is too busy trying to process stuff,
it can't send an ACK back to the RT source, which means that the RT source can't free up the memory for
those "already sent" objects. You might see RT queues on the sender side looking big, even though they have
been sent. (I don't recall if we saw this.)
They haven't been ack'd yet, so the source can't mark them as delivered and free them from the RTQ.

Enter heartbeats...
Heartbeats allow the source to notice when the sink is not responding.
The current setting for heartbeats is to send a ping every 15 seconds to the source
and then wait for 15 seconds more before we declare the sink as "gone".
If that happens, then we restart the RT source connection to the sink, which will
eventually kill that sink, but if the sink is not really gone, but just overloaded and buried by a really
huge mailbox, then it won't even get the heartbeat ping because the ping is at the back of the mailbox.
And thus it won't reply to the source in time.
So, bang - the connection gets killed.
But the sink doesn't know the connection is gone yet! So it stays up.
Now you have two "connections" on the sink side. One is real and one is stale and dying.
Eventually, the first sink connection will die
But it gets worse!
As soon as the second RT source starts up, it re-sends ALL of those messages that were never ACK'd.
And then that sink gets backed up...and the whole thing happens again.
Now the RT source is flooding the second connection and you know what happens next...the second
connection gets killed and we make a third, and so on. Really bad day for replication.
## Suggestions:

Back pressure!
- Using TCP in "active once" would apply back pressure with OS send buffers.
- Or maybe have the RT source use two windows of messages, like the old fullsync does...
  double buffering.
- Consider increasing the default HB timeout from 15 seconds to 30, but keep the HB at 15.

**Comment by buddhisthead** [comment]
Resolved by https://github.com/basho/riak_repl/issues/356

**Comment by jcapricebasho** [comment]
https://github.com/basho/riak_ee-issues/issues/9
