### ISSUE TITLE
bad call to timer:nowdiff causes frequent repl source reconnections to the sink

### ISSUE THREAD

**Issue by bowrocker** [basho/riak_repl#368]
In the context of performance testing 1.3.3 and patches for 1.3.2, set up 1 node clusters on r2s15 and r2s16 in the boston colo and built 1.3.3. During a basho_bench run, noticed source reconnections, and saw the following in the log on the source side:

2013-08-09 20:58:03.268 [error] <0.8060.154> gen_server <0.8060.154> terminated with reason: no function clause matching timer:now_diff({1376,96283,268662}, undefined) line 206
2013-08-09 20:58:03.271 [error] <0.8060.154> CRASH REPORT Process <0.8060.154> with 0 neighbours exited with reason: no function clause matching timer:now_diff({1376,96283,268662}, undefined) line 206 in gen_server:terminate/6 line 747
2013-08-09 20:58:03.271 [info] <0.23038.161>@riak_repl2_rtsource_conn:handle_call:208 Established realtime connection to site "r2s16" address 10.0.24.26:10016
2013-08-09 20:58:03.273 [error] <0.2063.0> Supervisor riak_repl2_rtsource_conn_sup had child "r2s16" started with riak_repl2_rtsource_conn:start_link("r2s16") at <0.8060.154> exit with reason no function clause matching timer:now_diff({1376,96283,268662}, undefined) line 206 in context child_terminated

The reconnects appeared to cause drops and errors on the source side:

realtime_queue_stats: [{bytes,720},
                       {max_bytes,104857600},
                       {consumers,[{"r2s16",
                                    [{pending,0},
                                     {unacked,0},
                                     {drops,2212510},
                                     {errs,18}]}]}]

**Comment by jonmeredith** [comment]
Based on the crash log entry

```
2013-08-09 20:35:51 =ERROR REPORT====
** Generic server <0.17043.129> terminating 
** Last message in was {tcp,#Port<0.16557>,<<0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0>>}
** When Server state == {state,"r2s16",{"10.0.24.26",10016},#Ref<0.0.45.214986>,ranch_tcp,#Port<0.16557>,{realtime,{1,1},{1,1}},<0.17061.129>,15000,15000,#Ref<0.0.49.60848>,{1376,94951,637085},119,<<>>}
** Reason for termination == 
** {function_clause,[{timer,now_diff,[{1376,94951,637698},undefined],[{file,"timer.erl"},{line,206}]},{riak_repl2_rtsource_conn,recv,2,[{file,"src/riak_repl2_rtsource_conn.erl"},{line,317}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,6
07}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
2013-08-09 20:35:51 =CRASH REPORT====
  crasher:
    initial call: riak_repl2_rtsource_conn:init/1
    pid: <0.17043.129>
    registered_name: []
    exception exit: {{function_clause,[{timer,now_diff,[{1376,94951,637698},undefined],[{file,"timer.erl"},{line,206}]},{riak_repl2_rtsource_conn,recv,2,[{file,"src/riak_repl2_rtsource_conn.erl"},{line,317}]},{gen_server,handle_msg,5,[{file,"gen_se
rver.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]},[{gen_server,terminate,6,[{file,"gen_server.erl"},{line,747}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
    ancestors: [riak_repl2_rtsource_conn_sup,riak_repl2_rtsource_sup,riak_repl2_rt_sup,riak_repl_sup,<0.793.0>]
    messages: [{tcp,#Port<0.16557>,<<0,0,0,1,0>>}]
    links: [<0.2064.0>,#Port<0.16557>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 24
    reductions: 2529203
  neighbours:
2013-08-09 20:35:51 =SUPERVISOR REPORT====
     Supervisor: {local,riak_repl2_rtsource_conn_sup}
     Context:    child_terminated
     Reason:     {function_clause,[{timer,now_diff,[{1376,94951,637698},undefined],[{file,"timer.erl"},{line,206}]},{riak_repl2_rtsource_conn,recv,2,[{file,"src/riak_repl2_rtsource_conn.erl"},{line,317}]},{gen_server,handle_msg,5,[{file,"gen_server
.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
     Offender:   [{pid,<0.17043.129>},{name,"r2s16"},{mfargs,{riak_repl2_rtsource_conn,start_link,["r2s16"]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
```

Given there's an entry in the hb_sent field, the only way I can see this happening is if there were two heartbeat messages in the same handle_info({tcp, Bin}, ...) clause.  In fact, there are 4.

```
(dev1@127.0.0.1)3> {ok, Msg1, Cont} = riak_repl2_rtframe:decode(<<0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0>>).
{ok,heartbeat,<<0,0,0,1,0,0,0,0,1,0,0,0,0,1,0>>}
(dev1@127.0.0.1)4> {ok, Msg2, Cont2} = riak_repl2_rtframe:decode(Cont).                                      
{ok,heartbeat,<<0,0,0,1,0,0,0,0,1,0>>}
(dev1@127.0.0.1)5> {ok, Msg3, Cont3} = riak_repl2_rtframe:decode(Cont2).
{ok,heartbeat,<<0,0,0,1,0>>}
(dev1@127.0.0.1)6> {ok, Msg4, Cont4} = riak_repl2_rtframe:decode(Cont3).
{ok,heartbeat,<<>>}
```

Something is not well - I wonder if it's something really weird like delay_send set true or something like that.

**Comment by Vagabond** [comment]
Can this be closed?

**Comment by cmeiklejohn** [comment]
Closing; resolved.
