### ISSUE TITLE
Backport "Fix typo in rt_heartbeat_ config vars" to 1.3.3

### ISSUE THREAD

**Issue by alexmoore** [basho/riak_repl#374]
@buddhisthead fixed a few typos for configuration variables in 33b8fbecd946a7d47563410ca5293a5074e03fd2. It would be nice to backport those to 1.3.3.

41st parameter tried to test RT repl with the heartbeat disabled by setting `rt_heartbeat_interval` to `undefined`, but kept running into our other existing issues since it wasn't actually getting disabled.

**Comment by lordnull** [comment]
The pull associated with this issue has been Merged, so this can be closed.
