### ISSUE TITLE
RTQ Overload Round up

### ISSUE THREAD

**Issue by lordnull** [basho/riak_repl#376]
Tracking the pull requests/tasks to get RTQ Overload protection done.
- [x] Riak Test: https://github.com/basho/riak_test/pull/354
- [x] Overload Protection Master: https://github.com/basho/riak_repl/pull/372
- [x] Overload Protection 1.4: #377 
- [x] Overload Protection 1.3: #378

**Comment by bowrocker** [comment]
+1

**Comment by lordnull** [comment]
Closing this up as everything has been merged.
