### ISSUE TITLE
Cluster Mgr Supervisor should register a name locator function.

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#428]
The supervisor, riak_core_cluster_mgr_sup, currently registers the default functions, but it needs to also register a cluster name locator. It could just call the riak_repl_app:register_cluster_name_locator(), which will handle all registration.

But something needs to re-register the "cluster_by_name" locator. Such could be accomplished like this:

```
Locator = fun(ClusterName, _Policy) ->
                      Ring = get_ring(),
                      Addrs = riak_repl_ring:get_clusterIpAddrs(Ring, ClusterName),
                      lager:debug("located members for cluster ~p: ~p", [ClusterName, Addrs]),
                      {ok,Addrs}
              end,
riak_core_connection_mgr:register_locator(?CLUSTER_NAME_LOCATOR_TYPE, Locator).
```

**Comment by cmeiklejohn** [comment]
If `riak_core_connection_mgr` dies, which is supervised by `riak_core_sup`, how will you know to call this function in repl, since you can't hardcode a call in `riak_core` to `riak_repl`?

**Comment by buddhisthead** [comment]
The cluster manager is supervised under riak_repl_sup/riak_core_cluster_mgr_sup. If the CM dies for any reason (including if the connection dies), then the riak_core_cluster_mgr_sup will restart it. Adding the registration there will resolve the locator.

**Comment by cmeiklejohn** [comment]
Nevermind, I assumed that _core_ supervised `riak_core_connection_mgr`, not _repl_.

**Comment by buddhisthead** [comment]
Ah boo. This solution is not going to work. We're going to need to use something less persistent such as @Vagabond suggested where we pass in locator functions when we need them. So, we're going to need to re-work the supervisor and registrations. I'm closing this one out to make a new one.
