### ISSUE TITLE
Replace registered 'locator' functions with passed-in functions for connection manager.

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#431]
With the application of https://github.com/basho/riak_repl/pull/398, we will no longer have the ability to restart the cluster manager (and hence re-register the locator) when the cluster manager connection crashes/restarts. Since the cluster manager connection will be in riak_core, and the cluster manager is riak_repl, we can't get supervision across them.

So instead, as @Vagabond has suggested, we should pass in our locator functions when they are needed. This will remove the need to register them at all. We have a macro that defines the locator, which we can replace with a fun that does the locating or call the right thing.

**Comment by cmeiklejohn** [comment]
Just noting this is currently broken on 2.0 and needs to be fixed.  Having a riak_test to ensure this would be a huge help.

**Comment by buddhisthead** [comment]
Well yeah, that's why it's an issue slated for 2.0 :-)

**Comment by cmeiklejohn** [comment]
The e-mails that GitHub generates for new issues don't contain the milestone information, so I just wanted to be explicit for those who didn't click through to the issue.

**Comment by cmeiklejohn** [comment]
Moving to 2.1 as part of the connection manager work.

**Comment by engelsanchez** [comment]
These modules were moved back from core to riak_repl, as there were many problems related to the move. Closing for now. Problems like this will be handle when the new networking layer is reworked.
