### ISSUE TITLE
Have aae_source handle not_built

### ISSUE THREAD

**Issue by jcapricebasho** [basho/riak_repl#471]
prepare_exchange state (https://github.com/basho/riak_repl/blob/develop/src/riak_repl_aae_source.erl#L177) needs to handle `not_built` in addition to `ok` and `already_locked` from the sink (https://github.com/basho/riak_repl/blob/develop/src/riak_repl_aae_sink.erl#L153).

**Comment by cmeiklejohn** [comment]
This was resolved as part of the AAE repl full sync work addressed in 1.4 and 2.0.
