### ISSUE TITLE
AAE Fullsync might deadlock in bi-directional replication

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_repl#499]
It appears that AAE fullsync is susceptible to a deadlock as written today, during bi-directional replication if the two sides both start the same partition at the same time. Because the aae source retries the remote lock forever, the two sides could fail to make progress.

The problem would be avoided if the aae fullsync source gave up it's local lock when it got `already_locked` from the remote and re-queued the partition for later. Funny that we have a comment in the code that says that.

**Comment by uwiger** [comment]
Probably much too late to start considering http://github.com/uwiger/locks, but it does support multi-node locking with deadlock resolution. To my knowledge, riak would be the first product to use it in anger, but it has no known bugs. ;-)

**Comment by buddhisthead** [comment]
@uwiger It's probably too late, but I'd like to look at the locks repo if it's public. I get a 404 when I follow that link.

**Comment by uwiger** [comment]
I first wrote 'locker' instead of 'locks'. The correct link is https://github.com/uwiger/locks, and it is public (MPL 2.0).

My intent is to use it in global gproc and in kvdb.

**Comment by buddhisthead** [comment]
@uwiger Cool. Thanks for the update. I'll have a look.

**Comment by cmeiklejohn** [comment]
This needs to be investigated for 2.0-beta.  Scheduling accordingly.

**Comment by cmeiklejohn** [comment]
Assigning to @cmeiklejohn.

**Comment by michellep-basho** [comment]
Hi Chris, do you have any updates on this?

thanks,
Michelle

**Comment by cmeiklejohn** [comment]
Not yet, but it's on the RC list so something this week or next.  Sorry, I'm the only one on repl working issues in the order they are assigned on GitHub.

Chris

**Comment by andrewjstone** [comment]
I'm taking this.

**Comment by andrewjstone** [comment]
I don't see how a deadlock can arise in the manner described in this issue. The following lines show that `already_locked` is handled in `prepare_exchange/2` Error clause, and the source exits instead of retrying.
https://github.com/basho/riak_repl/blob/develop/src/riak_repl_aae_source.erl#L197-L198

I suggest closing this unless it's been seen recently while testing or I'm missing something.

**Comment by andrewjstone** [comment]
Additionally, when the aae source exits, the monitor for the lock should fire and unlock the local tree as shown here: https://github.com/basho/riak_kv/blob/develop/src/riak_kv_index_hashtree.erl#L543-L546
and here https://github.com/basho/riak_kv/blob/develop/src/riak_kv_index_hashtree.erl#L365-L367

**Comment by cmeiklejohn** [comment]
Moved to the 2.1 milestone.

**Comment by engelsanchez** [comment]
I agree with Andrew here. There are no unlimited retries with a lock held going on here.  Closing unless new evidence emerges.
