### ISSUE TITLE
Investigate replication and replication_ssl riak_test failures

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_repl#572]
- http://giddyup.basho.com/#/projects/riak_ee/scorecards/94/94-2094-replication-centos-6-64
- http://giddyup.basho.com/#/projects/riak_ee/scorecards/94/94-2095-replication_ssl-centos-6-64

**Comment by kellymclaughlin** [comment]
[This](https://github.com/basho/riak_test/pull/566) PR addresses the failure of the `replication` test and some of the issues that the `replication_ssl` test was experiencing.

**Comment by jonmeredith** [comment]
Looks like still a few failures after #561 merged according to comments there.

**Comment by cmeiklejohn** [comment]
Do you mean #561 on a different repo?  The linked PR contains no comments.

**Comment by cmeiklejohn** [comment]
I'm taking this to investigate further.

**Comment by cmeiklejohn** [comment]
Actually, ignore that.  I'm not going to pick this up because it is repl v2 related, which has already been officially deprecated, given limited resources during the 2.0-RC cycle.  cc: @kellymclaughlin @jonmeredith
