### ISSUE TITLE
Should we fullsync_on_connect set 'off' on default?

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_repl#573]
This is just my concern and may include my misunderstanding...
fullsync_on_connect looks to cause fullsync frequently. So I'm wondering it should be 'false' on default.

When fullsync is triggered by fullsync_on_connect:
- stopped cluster_leader on site side. (ex. rolling upgrade process causes fullsync frequently. In the worst case, number of running fullsync may be riak node number?)
- cluster_leader leaved from site side.
- node failure of cluster_leader on site side.
- recovered from network partition.
- recovered from cluster failure on site side.

Especially I'm concerned about the case on rolling upgrade...

**Comment by cmeiklejohn** [comment]
Adding to the RC milestone.

**Comment by cmeiklejohn** [comment]
I'll defer this one to @jonmeredith.

**Comment by jonmeredith** [comment]
Difficult one.  I think what we really want is fullsync-if-you-dropped-from-the-realtime-queue-or-a-node-died.

If we change the default now, it means we'd need to be sure people read the release notes, and I'm not sure they would.  If a fullsync was running before the disconnection, then it will resume after.  If the network is partitioned, you're right it will start a fullsync on both sides of the partition, which is undesirable, but not terrible as it sends data one-way and only the data it has.

The config comments are a little misleading, and makes it seem like the fullsync happens only on the very first connection to the remote cluster.  It should probably say something like "Start a fullsync whenever the cluster manager connection is re-established". (thoughts @jd?)

```
   %% Whether to initiate a fullsync on initial connection from the
   %% sink cluster.
   {fullsync_on_connect, true},
```

I'd vote against a change of defaults until we have longer to think about it, and possibly implement something more useful.

**Comment by ksauzz** [comment]
I also defer to Jon's decision. Certainly, a change of default causes unexpectedly behaviour and surprise for customers. Indeed, the main purpose of the feature is so helpful for MDC and my concern is just about its frequency.
Thanks for spending time for this.
