### ISSUE TITLE
/riak-repl/stats returns last_fullsync_started as a string of bytes

### ISSUE THREAD

**Issue by cipy** [basho/riak_repl#580]
Hi,

http://localhost:8098/riak-repl/stats returns `last_fullsync_started` as a string of bytes (see below) instead of the more human readable: <<"Mon, 05 May 2014 07:37:55 GMT">>

Thanks,
Ciprian

```
     "last_fullsync_started" : [
        77,
        111,
        110,
        44,
        32,
        48,
        53,
        32,
        77,
        97,
        121,
        32,
        50,
        48,
        49,
        52,
        32,
        48,
        55,
        58,
        51,
        55,
        58,
        53,
        53,
        32,
        71,
        77,
        84
     ],
```

**Comment by cipy** [comment]
And If I look at the offcial doc http://docs.basho.com/riakee/1.4.8/cookbooks/Multi-Data-Center-Replication-Statistics/#Fullsync-Replication-Statistics the parameter `last_fullsync_started` does not exist, but a parameter `fullsync_start_time` should exist - which is not the case in the actual output.

**Comment by cipy** [comment]
cloned as https://github.com/basho/riak_ee-issues/issues/16

**Comment by binarytemple** [comment]
I don't want to put pressure on anyone but client is looking for ETA on this bug. Has a fix been scheduled?

**Comment by cmeiklejohn** [comment]
This would involve shipping a 1.4.9 release unless we push a hotfix to the customer.  I'm not sure where that is in the schedule right now, @jonmeredith, @jaredmorrow?  Also, have we confirmed if this is a problem in 2.0 as well?

**Comment by Vagabond** [comment]
I have PRs to fix this in 1.4 and 2.0: #583 #584

**Comment by binarytemple** [comment]
Sorry guys, should I create a new ticket. This is actually a two part bug, firstly there was the issue of datetime formatting, but secondly there was the issue of 'last_fullsync_started' coming back as undefined. I'm going to ship the patch to the customer and tell him we're looking into the second issue.

**Comment by Vagabond** [comment]
If there has not been a fullsync started, yes it will come back as undefined.
