### ISSUE TITLE
Feature request: Default deny behavior of replication bucket property

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_repl#582]
Matt R from Voxer has requested a flag to, by default, disable the replication property on buckets. This can be accomplished with default bucket props but not in their case as they are moving from an OSS to EE Riak and already have all buckets defined. They have a few hundred buckets and only want to replication ~10.

**Comment by cmeiklejohn** [comment]
What version of Riak EE?

**Comment by jonmeredith** [comment]
For Voxer now, seems like it would be a relatively easy ring_trans to fix their custom buckets.

For the future, will bucket types provide the facility they need?  i.e. is this something we should fix?  Marking against 2.1 for future discussion.

**Comment by bsparrow435** [comment]
Closing. Resolved with custom ring transform and addressed with bucket types in 2.0+
