### ISSUE TITLE
v2 post commit hook removal problem

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_repl#588]
Because of this line https://github.com/basho/riak_repl/blob/52bc3fd0de1791bbfcded96271a8e5e5964ca03d/src/riak_repl.erl#L69 the repl fixup that should remove hooks for the older version of replication when it's been disabled actually doesn't.  That line is stripping out hooks for modes currently active where it should remove any that repl has ever used in the past to be safe.  Then the logic in fixup would re-add only the ones for the current modes.

This was discovered in a customer issue when the objects_dropped_no_leader stat kept going up even after repl v2 was removed from the mode list. That stat is v2 only.

**Comment by cmeiklejohn** [comment]
I thought you already ported a fix over for this, no?

**Comment by engelsanchez** [comment]
Yes. This was fixed by https://github.com/basho/riak_repl/pull/589 and was ported to 1.4 to be included in 1.4.9. Closing.
