### ISSUE TITLE
Change trim_q_entries/4 lager:notice to lager:debug

### ISSUE THREAD

**Issue by jcapricebasho** [basho/riak_repl#603]
This lager:notice call should be switched to lager:debug https://github.com/basho/riak_repl/blob/develop/src/riak_repl2_rtq.erl#L651, as it can fill up logs when the queue is full and trimming objects.

**Comment by jonmeredith** [comment]
Agreed - we shouldn't log anything by default that can occur per-request in
a valid mode of operation.

On Wed, Jun 18, 2014 at 2:40 PM, jcapricebasho notifications@github.com
wrote:

> This lager:notice call should be switched to lager:debug
> https://github.com/basho/riak_repl/blob/develop/src/riak_repl2_rtq.erl#L651,
> as it can fill up logs when the queue is full and trimming objects.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak_repl/issues/603.

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by jcapricebasho** [comment]
PR #604

**Comment by jcapricebasho** [comment]
PR merged, closing issue.
