### ISSUE TITLE
Mismatched bucket types cause realtime replication to fill RTQ

### ISSUE THREAD

**Issue by jonmeredith** [basho/riak_repl#611]
If the bucket types are different between two clusters, realtime replication does
not acknowledge the incompatible object from the realtime sink to the realtime source,
causing the realtime queue to grow to maximum capacity and drop objects.

Root cause is the DoneFun isn't called immediately during the error case.

https://github.com/basho/riak_repl/pull/490/files#diff-4ca8b1cb0696e26e1d5024bc67e155d2R295

With the log level set at info, on a loaded cluster many log entries will be written
clearing it out.  The log message does not provide details on which bucket/bucket type
has issues.

Recommend

a) Restrict frequency of log message and perhaps keep a counter of occurrence (by bucket).
(Perhaps start keeping count with dict:add_counter, fire a timer after 10s or 60s to report totals and clear it/log changes)

b) Modify the r_t to verify that the RTQ is drained when testing bucket types.

**Comment by bowrocker** [comment]
Fixes and riak test merged, closing.
