### ISSUE TITLE
Create a `last_fullsync_completed` statistic

### ISSUE THREAD

**Issue by angrycub** [basho/riak_repl#634]
A customer has requested that there be a `last_fullsync_completed` statistic because the `last_fullsync_started` statistic clears itself out when there is not a currently running fullsync.

**Comment by angrycub** [comment]
See issue at https://basho.zendesk.com/agent/tickets/8987

**Comment by engelsanchez** [comment]
Micah has worked on a solution for this in #642 that we'll review and try to get in 2.0.4
