### ISSUE TITLE
Server Stats and Start/Stop/Pause FullSync Do Not Work

### ISSUE THREAD

**Issue by ghost** [basho/riak_repl#65]
Previously, `riak_repl_server_sup` handled `riak_repl_tcp_server`. When the fullsync and stats commands were run from `riak_repl_console`, the following was ran:

``` erlang
server_pids() ->
    [P || {_,P,_,_} <- supervisor:which_children(riak_repl_server_sup), P /= undefined].
```

This listed the `riak_repl_tcp_server` children, and then the commands were sent like so:

``` erlang
start_fullsync([]) ->
    [riak_repl_tcp_server:start_fullsync(Pid) || Pid <- server_pids()],
    ok.
```

However, this has changed. Instead of calling `riak_repl_server_sup:start_server/1`, it is called via `riak_repl_listener_sup:ensure_listeners/1`, which calls `riak_repl_listener_sup:start_listener/1`:

``` erlang
start_listener(Listener = #repl_listener{listen_addr={IP, Port}}) ->
    case riak_repl_util:valid_host_ip(IP) of
        true ->
            lager:info("Starting replication listener on ~s:~p",
                [IP, Port]),
            {ok, RawAddress} = inet_parse:address(IP),
            ranch:start_listener(Listener, 10, ranch_tcp,
                [{ip, RawAddress}, {port, Port}], riak_repl_tcp_server, []);
        _ ->
            lager:error("Cannot start replication listener "
                "on ~s:~p - invalid address.",
                [IP, Port])
    end.
```

You'll note that it called `ranch:start_listener/6`. This is a new dependency, managing socket connection pools. The source is located at https://github.com/extend/ranch. 

With this, calling `supervisor:which_children(riak_repl_server_sup).` results in nothing:

``` erlang
[]
```

This is because children are no longer spawned under `riak_repl_server_sup`. 

However, unlike listing supervisors under `riak_repl_server_sup`, which had `riak_repl_tcp_server` as a direct child, `ranch` operates differently.

Note the following:

``` erlang
supervisor:which_children(ranch_sup).               
[{{ranch_listener_sup,#repl_listener{nodename = 'dev1@127.0.0.1',
                                     listen_addr = {"127.0.0.1",9010}}},
  <0.31129.0>,supervisor,
  [ranch_listener_sup]}]
```

This has a `ranch_listener_sup` as a child. Digging further in:

``` erlang
supervisor:which_children(c:pid(0,31129,0)).
[{ranch_acceptors_sup,<0.31132.0>,supervisor,
                      [ranch_acceptors_sup]},
 {ranch_conns_sup,<0.31131.0>,supervisor,[ranch_conns_sup]},
 {ranch_listener,<0.31130.0>,worker,[ranch_listener]}]
```

It turns out that `riak_repl_tcp_server` is spawned from `ranch_conns_sup`:

``` erlang
supervisor:which_children(c:pid(0,31131,0)).
[{undefined,<0.31145.0>,worker,[ranch_conns_sup]}]
```

We can then query `riak_repl_tcp_server` with this pid:

``` erlang
riak_repl_tcp_server:status(c:pid(0,31145,0)).
{status,[{node,'dev1@127.0.0.1'},
         {site,"dev1-dev2-dev3"},
         {strategy,riak_repl_keylist_server},
         {fullsync_worker,<0.31146.0>},
         {dropped_count,0},
         {queue_length,0},
         {queue_byte_size,0},
         {state,wait_for_partition}]}
```

So the interface to `riak_repl_tcp_server` still works, however the migration to using `ranch` has made querying this process troublesome.

**Comment by Vagabond** [comment]
Fixed by #67
