### ISSUE TITLE
Realtime replication for blocks, and other redesign [JIRA: RCS-110]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_repl#654]
Currently, only buckets, users and manifests are replicated in realtime.

It would be good to start discussing on:
- add realtime replication on blocks
- whether do we add switch on replication usage/storage stats
- whether do we add switch on GC bucket

This should involve code change in repl, so linking to riak_repl repo (not CS repo).

**[Created in JIRA by Kota Uenishi]**

**Comment by Basho-JIRA** [comment]
Actually the work has already been merged to 2.1 branch, so it'll be included in Riak 2.1.2. 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by shino** [comment]
cross reference : riak_test in riak_cs repo https://github.com/basho/riak_cs/pull/1146

**Comment by Basho-JIRA** [comment]
Release note: Add configuration items to replicate blocks in realtime replication ( `replicate_cs_blocks_realtime` ) and to replicate block tombstones in realtime replication ( `replicate_cs_block_tombstone` ). The former is to relieve load in fullsync replication (whose price is longer RTQ in realtime replication and risk to drop manifests or other important keys), which is `false` by default. The latter is to relieve load generated by GC in sink cluster of duplicate efforts to reclaim data, which is `true` by default. Both configuration are to be set in `advanced.config` of Riak node, not Riak CS configuration. Note that they are available in Riak 2.1.2 or newer and default behaviour on transferring block tombstones has changed from previous Riak releases ( Riak KV 2.1.2 or older).

c.f. description in https://github.com/basho/riak_repl/pull/678 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by kuenishi** [comment]
Followed by https://github.com/basho/riak_repl/pull/709
