### ISSUE TITLE
improve RTQ visibility and/or add ability to remove blocked object [JIRA: RIAK-1818]

### ISSUE THREAD

**Issue by binarytemple** [basho/riak_repl#681]
REDACTED (during healthcheck and training session) and [Netic](https://basho.zendesk.com/agent/tickets/10695) have both (repeatedly) asked for this functionality. 

They frequently see:
- The realtime queue size grows
- Objects are discarded because the queue reaches it's maximum size
- Updates fail to reach the sink cluster 
- Suddenly the queue size drops to zero and replication proceeds as before

They (REDACTED) suspect that large objects are blocking up the replication, perhaps in conjunction with heartbeat messages not making it back to the source node.

They would like functionality that would enable them to:
- List the objects that are in the realtime replication queue, with object identifier and size.
- Remove an object, given it's identifier 

In a perfect world we would provide a command line interface for performing these operations. 

In practice, given the level of competence of operators of these systems, the ability to manipulate the ETS table holding the replication queue would probably suffice, CSE staff could provide the appropriate snippets. 

However it is not possible to do so, because the ETS table has [been marked private, which means that it is only accessible to it's enclosing module](https://github.com/basho/riak_repl/blob/develop/src/riak_repl2_rtq.erl#L53). As it's a black box, we have hit a brick wall in terms of diagnosis.

**Comment by binarytemple** [comment]
More info I received from Sparrow indicates my initial diagnosis may have been incorrect..

`riak_repl2_rtq.erl` makes use of it's own ETS table, [`rtq_overload_ets`](https://github.com/basho/riak_repl/blob/0adc0851a60517adeb91c6422daac2ad17a6431d/src/riak_repl2_rtq.erl#L106-106). I will continue to investigate the implementation.

**Comment by jonmeredith** [comment]
Fwiw, you can see the contents of the realtime queue with `riak_repl2_rtq:dumpq/0`.  Perhaps something that allowed you to fold over the queue and collect summary stats would be useful without retrieving the whole thing.
