### ISSUE TITLE
Memory Leak in riak_core_connection_mgr_stats [JIRA: RIAK-2231]

### ISSUE THREAD

**Issue by ian-mi** [basho/riak_repl#711]
Whenever there is a conn_error, riak_core_connection_mgr_stats will create or update a stat which includes the entire error: https://github.com/basho/riak_repl/blob/develop/src/riak_core_connection_mgr_stats.erl#L231-L239. However, in the case of a noproc error, the PID and port number will be included as part of this error tuple essentially making this error unique. When a node hits such an error repeatedly this can lead to hundreds of thousands folsom spirals and counters being created and until all available memory is used by these statistics. Rather than store the entire Error tuple in the statistic, perhaps only the error slogan, of which there should only be a finite number, should be included?

**Comment by Basho-JIRA** [comment]
A patch for this was built today. 

**_[posted via JIRA by Seema Jethani]**_

**Comment by Basho-JIRA** [comment]
Merged into 2.1 branch 

**_[posted via JIRA by Douglas Rohrer]**_
