### ISSUE TITLE
Incorrect return from `handle_info` calling log spam

### ISSUE THREAD

**Issue by russelldb** [basho/riak_repl#786]
Reported by @martinsumner https://github.com/basho/riak_repl/blob/develop/src/riak_core_service_conn.erl#L132-L134

The return is incorrect, should be `{stop, Reason, StateName}`

**Comment by russelldb** [comment]
NOTE: there is another one on l128 too

**Comment by martinsumner** [comment]
https://github.com/basho/riak_repl/blob/develop-2.9/src/riak_core_service_conn.erl#L128-L134
